/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWorld */

#ifndef _Included_HelloWorld
#define _Included_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloWorld
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloWorld_print
  (JNIEnv *, jobject);

/*
 * Class:     HelloWorld
 * Method:    dobro
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_HelloWorld_dobro
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
